imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar:              true
    intercept_redirects:  false

monolog:
    channels:
        - 'twitter_api'
        - 'status'
    handlers:
        sentry: "%monolog_sentry_logging_handler%"
        main:   "%monolog_main_logging_handler%"
