imports:
    - { resource: config_dev.yml }
    - { resource: ../parameters_test.yml }

parameters:
    main_log_level:     'debug'
    sentry_log_level:   'error'

framework:
    test:           ~
    session:
        storage_id: session.storage.mock_file
