---
- name: Install Apache
  sudo: yes
  apt: pkg=apache2 state=latest

- name: Install Apache Modules
  apache2_module: state=present name={{ item }}
  notify: restart apache
  with_items:
    - actions
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- name: Remove php5_module
  sudo : yes
  apt:
    name: libapache2-mod-php5
    purge: yes

- name: Install FastCGI
  sudo : yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libapache2-mod-fastcgi

- name: Ensure php5 module is absent
  apache2_module: state=absent name=php5
  notify: restart apache

- name: Change default apache2.4 site
  sudo: yes
  template: src=vhost24.conf.tpl dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache

- name: Configure PHP fpm
  sudo: yes
  template: src=php-fpm.conf.tpl dest=/etc/apache2/conf-available/php-fpm.conf

- name: Fetch Sven Hoexter PPA key
  sudo: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0E40A6FE2B8B35A62079DBA85359CA145B1AFC7F
    state: present

- name: Install Sven Hoexter PPA
  sudo: yes
  apt_repository:
    repo: 'ppa:sven-timegate/ppa'
    state: present

- name : Install realdoc module
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: libapache2-mod-realdoc
    state: present
  notify: restart apache

- name: Enable PHP fpm configuration
  sudo: yes
  file:
    src: /etc/apache2/conf-available/php-fpm.conf
    dest: /etc/apache2/conf-enabled/php-fpm.conf
    owner: root
    group: root
    state: link
  notify: restart apache

- name: Update ports
  sudo: yes
  template: src=ports.conf.tpl dest=/etc/apache2/ports.conf
  notify: restart apache

- name: Flush handlers to apply config changes
  meta: flush_handlers
