parameters:
    api_access_token:               %oauth_access_token%
    api_client_id:                  %oauth_client_id%
    api_client_secret:              %oauth_client_secret%

    app_version:                    TF8

    locale:                         en

    framework_secret:               %framework.secret%

    quality_assurance_password:     ~

    test_database_memory:           false
    test_database_path:             %kernel.cache_dir%/devobsboard.db
