aggregation:
    resource: WeavingTheWeb\Bundle\ApiBundle\Controller\AggregationController
    type:     annotation

job:
    resource: WeavingTheWeb\Bundle\ApiBundle\Controller\JobController
    type:     annotation

oauth:
    resource: WeavingTheWeb\Bundle\ApiBundle\Controller\OAuthController
    type:     annotation

perspective:
    resource: WeavingTheWeb\Bundle\ApiBundle\Controller\PerspectiveController
    type:     annotation
