parameters:
    command.map_aggregate_status_collection.class:  'App\StatusCollection\Mapping\Command\MapAggregateStatusCollectionCommand'
    command.map_status_collection.class:            'App\StatusCollection\Mapping\Command\MapStatusCollectionCommand'
    command.select_status_collection.class:         'App\StatusCollection\Command\SelectStatusCollectionCommand'

services:
    command.select_status_collection:
        class:                       "%command.select_status_collection.class%"
        properties:
            statusRepository:       "@weaving_the_web_twitter.repository.status"
        tags:
            - { name: 'console.command' }

    command.map_status_collection:
        class:                      "%command.map_status_collection.class%"
        properties:
            statusRepository:       "@weaving_the_web_twitter.repository.status"
            refreshStatusMapping:   "@mapping.refresh_status"
            oauthToken:             "%weaving_the_web_twitter.oauth_token.default%"
            oauthSecret:            "%weaving_the_web_twitter.oauth_secret.default%"
        tags:
            - { name: 'console.command' }

    command.map_aggregate_status_collection:
        class:                      "%command.map_aggregate_status_collection.class%"
        properties:
            statusRepository:       "@weaving_the_web_twitter.repository.status"
            refreshStatusMapping:   "@mapping.refresh_status"
            oauthToken:             "%weaving_the_web_twitter.oauth_token.default%"
            oauthSecret:            "%weaving_the_web_twitter.oauth_secret.default%"
        tags:
            - { name: 'console.command' }
