services:
    mapping.identity:
        class: 'App\Status\Mapping\IdentityMapping'

    mapping.refresh_status:
        class: 'App\Status\Mapping\RefreshStatusMapping'
        arguments:
            - '@weaving_the_web_twitter.api_accessor'
        properties:
            logger:             '@monolog.logger.status'
            statusRepository:   '@weaving_the_web_twitter.repository.status'
