---
- name: Install Debconf utils
  sudo: yes
  apt: pkg=debconf-utils state=latest

- name: Preseed PHPMyAdmin installation
  shell: >
      /bin/bash -c 'echo "phpmyadmin phpmyadmin/internal/skip-preseed boolean true" | debconf-set-selections &&
      echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect" | debconf-set-selections &&
      echo "phpmyadmin phpmyadmin/dbconfig-install boolean false" | debconf-set-selections &&
      echo "phpmyadmin phpmyadmin/db/dbname phpmyadmin" | debconf-set-selections &&
      echo "phpmyadmin phpmyadmin/db/app-user phpmyadmin" | debconf-set-selections'

- name: Install PHPMyAdmin
  sudo: yes
  apt: pkg=phpmyadmin state=latest

- name: Symlink PHPMyAdmin Apache configuration
  sudo: yes
  file:
    src: /etc/phpmyadmin/apache.conf
    dest: /etc/apache2/conf-available/phpmyadmin.conf
    owner: root
    group: root
    state: link

- name: Enable Apache PHPMyAdmin configuratioon
  sudo: yes
  shell: a2enconf phpmyadmin
  notify: restart apache

- name: Flush handlers to apply config changes
  meta: flush_handlers

